/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef AGGIORNAMENTI_PRIVATE_H
#define AGGIORNAMENTI_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.1"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	1
#define COMPANY_NAME	""
#define FILE_VERSION	"1.2"
#define FILE_DESCRIPTION	"Chat che usa le socket"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"© Copyright 2011-2013"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Blackname"
#define PRODUCT_VERSION	"1.2"

#endif /*AGGIORNAMENTI_PRIVATE_H*/
